In [7]:
import numpy as np

In [8]:
import matplotlib.pyplot as plt

In [9]:
import pandas as pd

In [11]:
excelfile=r"/Users/jc/Projects/Mini-Challenge-1/Data Manipulation/IndividualRecords(Modified).csv";

In [14]:
df = pd.read_csv(excelfile)
df

/Users/jc/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (104,106,107) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ID,CarType,EnterDate,EnterTime,length,totalTime,N1,dt1,N2,dt2,...,N47,dt47,N48,dt48,N49,dt49,N50,dt50,N51,dt51_N52_dt52_N53_dt53_N54_dt54_N55_dt55_N56_dt56_N57_dt57_N58_dt58_N59_dt59_N60_dt60_N61_dt61_N62_dt62_N63_dt63_N64_dt64_N65_dt65_N66_dt66_N67_dt67_N68_dt68_N69_dt69_N70
0,20152930032938-338,1,2015-05-30,15:29:38,12,249644.0,E3,1257.0,GG1,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20153118013100-425,2,2015-07-18,13:31:00,6,285897.0,E2,788.0,GG6,500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20150909100908-893,1,2015-08-09,10:09:08,12,133812.0,E4,592.0,GG5,686.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20153824023844-286,1,2015-09-24,02:38:44,2,1408.0,E0,1408.0,E3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20153111063125-468,2,2015-07-11,06:31:25,6,182098.0,E1,720.0,GG7,557.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,20154502084548-823,3,2015-08-02,08:45:48,6,107086.0,E1,1028.0,C0,103579.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,20155924055911-559,1,2015-08-24,17:59:11,10,258603.0,E1,625.0,C3,254544.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,20150229070248-397,1,2015-08-29,07:02:48,11,274068.0,E3,816.0,GG7,539.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,20150831070819-751,2,2015-05-31,07:08:19,7,3330.0,E3,1341.0,GG1,171.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,20155525065551-662,1,2015-07-25,06:55:51,14,201736.0,E1,792.0,GG7,429.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,20150228020218-410,1,2015-06-28,14:02:18,9,3342.0,E1,703.0,GG7,382.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,20163206073247-445,4,2016-02-06,19:32:47,4,1904.0,E1,759.0,GG7,411.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,20161730081727-734,2P,2016-05-30,08:17:27,49,31897.0,B,105.0,G8,685.0,...,GG5,684.0,G8,109.0,B,NaN,NaN,NaN,NaN,NaN
13,20152918102936-198,2,2015-06-18,10:29:36,8,3466.0,E1,749.0,GG7,406.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,20151710051755-835,3,2015-07-10,17:17:55,16,99890.0,E2,1100.0,GG2,176.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,20163426093457-747,2P,2016-04-26,09:34:57,20,8919.0,B,87.0,G8,289.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,20152119012112-241,1,2015-06-19,13:21:12,10,94848.0,E1,384.0,C4,91419.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,20153705023701-460,1,2015-07-05,14:37:01,12,78141.0,E2,1317.0,GG2,212.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,20154219104241-223,1,2015-07-19,10:42:41,12,190268.0,E0,775.0,GG4,435.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20151510121543-670,3,2015-07-10,12:15:43,13,258367.0,E0,756.0,GG4,424.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20160408060432-898,6,2016-03-08,18:04:32,2,1314.0,E4,1314.0,E2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,20150216120249-701,1,2015-07-16,12:02:49,6,1638.0,E2,1077.0,GG2,172.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,20155422015409-486,1,2015-07-22,01:54:09,2,1043.0,E4,1043.0,E2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,20152030032023-389,1,2015-07-30,15:20:23,6,2877.0,E4,624.0,GG5,814.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,20152923102955-348,2,2015-07-23,10:29:55,11,81547.0,E1,861.0,GG7,466.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,20154727034733-671,2,2015-08-27,15:47:33,11,93802.0,E2,1099.0,GG2,176.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,20152614052608-658,1,2015-07-14,17:26:08,10,76709.0,E1,501.0,C4,72225.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,20150914030946-615,1,2015-09-14,15:09:46,18,8593.0,E4,688.0,GG5,796.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,20150723110714-736,3,2015-09-23,23:07:14,2,1356.0,E0,1356.0,E3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,20153812043859-808,2,2015-07-12,04:38:59,3,1509.0,E3,802.0,GG7,707.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18715,20164014014005-279,5,2016-05-14,01:40:05,7,2816.0,E4,553.0,GG5,638.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18716,20153229013212-110,1,2015-08-29,13:32:12,12,423505.0,E3,830.0,GG7,563.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18717,20154326104345-896,2,2015-09-26,10:43:45,11,4400.0,E1,698.0,GG7,380.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18718,20153014093042-799,3,2015-06-14,21:30:42,9,3411.0,E4,553.0,GG5,639.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18719,20153328023337-626,3,2015-07-28,02:33:37,9,3496.0,E1,736.0,GG7,400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18720,20164319034355-175,2,2016-05-19,15:43:55,7,194163.0,E1,835.0,GG7,646.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18721,20153316063347-434,3,2015-09-16,18:33:47,9,3502.0,E1,739.0,GG7,400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18722,20155324075359-504,4,2015-08-24,19:53:59,6,2964.0,E2,1197.0,GG2,193.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18723,20151329081357-856,6,2015-06-29,20:13:57,8,3991.0,E2,1326.0,GG2,213.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18724,20151027041058-551,1,2015-08-27,16:10:58,6,2737.0,E2,836.0,GG6,532.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18725,20151229041225-130,1,2015-06-29,16:12:25,17,409983.0,E2,1401.0,GG2,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18726,20150110050107-785,1,2015-05-10,17:01:07,2,1257.0,E0,1257.0,E3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18727,20151727081750-912,1,2015-07-27,08:17:50,12,179918.0,E3,1161.0,GG1,148.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18728,20153215073237-222,3,2015-05-15,07:32:37,6,256802.0,E1,787.0,GG7,610.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18729,20163324073336-290,1,2016-02-24,07:33:36,6,1609.0,E0,79.0,GG1,139.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18730,20151123071139-244,5,2015-08-23,07:11:39,9,4329.0,E4,700.0,GG5,811.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18731,20165313095326-823,1,2016-05-13,09:53:26,12,284002.0,E1,872.0,GG7,675.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18732,20152229062205-244,1,2015-07-29,06:22:05,11,2713.0,E4,350.0,GG6,467.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18733,20153507023520-378,1,2015-09-07,02:35:20,3,1707.0,E3,907.0,GG7,800.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18734,20155301025312-741,4,2015-05-01,02:53:12,7,3531.0,E3,1423.0,GG1,181.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18735,20154017024042-674,5,2015-08-17,14:40:42,6,2868.0,E2,1158.0,GG2,187.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18736,20153518113519-608,1,2015-08-18,11:35:19,11,176075.0,E3,814.0,GG7,750.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18737,20152823032832-378,2,2015-10-23,15:28:32,12,60554.0,E4,568.0,GG5,656.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18738,20151423021424-22,4,2015-07-23,02:14:24,2,1116.0,E2,1116.0,E4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18739,20162725032738-617,1,2016-02-25,15:27:38,6,3223.0,E3,1339.0,GG1,170.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18740,20154005024018-445,1,2015-06-05,14:40:18,7,289532.0,E0,840.0,GG4,473.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18741,20151307121323-821,1,2015-08-07,12:13:23,18,125601.0,E4,640.0,GG5,741.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18742,20152027112018-673,1,2015-07-27,23:20:18,8,3379.0,E2,1121.0,GG2,180.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18743,20153229043251-293,1,2015-07-29,16:32:51,12,522928.0,E0,724.0,GG4,406.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18744,20155812095815-41,4,2015-07-12,09:58:15,2,1300.0,E2,1300.0,E4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
if(col)